[package]
name = "mike"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
cpal = "0.16.0"
# pipewire = "0.8.0"  # Disabled for now

[[bin]]
name = "receiver"
path = "src/bin/receiver.rs"

[[bin]]
name = "transmitter"
path = "src/bin/transmitter.rs"
